#include "Read_write_test.h"


void TEST_READ_WRITE() {

 std::cout << "Test Read_Write.cpp" << std::endl;
 
 std::cout << "Test Read_Write.cpp Function: Read()" << std::endl;
 
 std::string FileNameToRead = "TXT_for_test/TEST_READ.txt";
 std::string FileNameToWrite = "TXT_for_test/TEST_WRITE.txt";
 
std::unordered_map<std::string, std::unordered_set<std::string>> wordRead = {
    {"humour", {"and"}},
    {"(injected", {"humour"}},
    {"passages,", {"and"}},
    {"an", {"unknown"}},
    {"sheets", {"containing"}},
    {"unchanged.", {"It"}},
    {"text", {"ever", "of"}},
    {"typesetting,", {"remaining"}},
    {"industry's", {"standard"}},
    {"leap", {"into"}},
    {"centuries,", {"but"}},
    {"content", {"here',", "of"}},
    {"'Content", {"here,"}},
    {"more-or-less", {"normal"}},
    {"1960s", {"with"}},
    {"was", {"popularised"}},
    {"specimen", {"book."}},
    {"has", {"a", "survived", "been"}},
    {"typesetting", {"industry."}},
    {"in", {"their", "the"}},
    {"purpose", {"(injected"}},
    {"manyweb", {"sites"}},
    {"it", {"look", "has", "to"}},
    {"dummy", {"text"}},
    {"since", {"the"}},
    {"Letraset", {"sheets"}},
    {"book.", {"It"}},
    {"is", {"that", "a", "simply"}},
    {"like", {"readable", "Aldus"}},
    {"also", {"the"}},
    {"only", {"five"}},
    {"to", {"using", "make"}},
    {"fact", {"that"}},
    {"industry.", {"Lorem"}},
    {"looking", {"at"}},
    {"into", {"electronic"}},
    {"uncover", {"manyweb"}},
    {"of", {"letters,", "a", "Lorem", "Letraset", "using", "type", "the"}},
    {"essentially", {"unchanged."}},
    {"survived", {"not"}},
    {"took", {"a"}},
    {"opposed", {"to"}},
    {"make", {"a"}},
    {"desktop", {"publishing"}},
    {"be", {"distracted"}},
    {"when", {"looking", "an"}},
    {"and", {"the", "a", "web", "more", "scrambled", "typesetting"}},
    {"1500s,", {"when"}},
    {"not", {"only"}},
    {"letters,", {"as"}},
    {"the", {"readable", "like).", "release", "1960s", "leap", "1500s,", "industry's", "printing"}},
    {"standard", {"dummy"}},
    {"publishing", {"packages", "software"}},
    {"electronic", {"typesetting,"}},
    {"at", {"its"}},
    {"It", {"was", "has"}},
    {"their", {"infancy.", "default"}},
    {"Lorem", {"Ipsum.It", "Ipsum"}},
    {"look", {"like"}},
    {"web", {"page"}},
    {"a", {"search", "more-or-less", "page", "reader", "long", "type", "galley"}},
    {"scrambled", {"it"}},
    {"remaining", {"essentially"}},
    {"search", {"for"}},
    {"simply", {"dummy"}},
    {"versions", {"have", "of"}},
    {"been", {"the"}},
    {"more", {"recently"}},
    {"galley", {"of"}},
    {"Various", {"versions"}},
    {"readable", {"English.", "content"}},
    {"have", {"evolved"}},
    {"containing", {"Lorem"}},
    {"reader", {"will"}},
    {"with", {"desktop", "the"}},
    {"but", {"also"}},
    {"by", {"accident,", "the"}},
    {"ever", {"since"}},
    {"type", {"specimen", "and"}},
    {"recently", {"with"}},
    {"popularised", {"in"}},
    {"software", {"like"}},
    {"Aldus", {"PageMaker"}},
    {"Ipsum", {"as", "passages,", "has", "is"}},
    {"including", {"versions"}},
    {"for", {"'lorem"}},
    {"Ipsum.It", {"is"}},
    {"printer", {"took"}},
    {"long", {"established"}},
    {"established", {"fact"}},
    {"on", {"purpose"}},
    {"its", {"layout."}},
    {"using", {"'Content", "Lorem"}},
    {"that", {"it", "a"}},
    {"'lorem", {"ipsum'"}},
    {"release", {"of"}},
    {"will", {"uncover", "be"}},
    {"distracted", {"by"}},
    {"page", {"editors", "when"}},
    {"layout.", {"The"}},
    {"editors", {"now"}},
    {"point", {"of"}},
    {"five", {"centuries,"}},
    {"normal", {"distribution"}},
    {"distribution", {"of"}},
    {"as", {"their", "opposed"}},
    {"packages", {"and"}},
    {"here,", {"content"}},
    {"here',", {"making"}},
    {"The", {"point"}},
    {"still", {"in"}},
    {"making", {"it"}},
    {"unknown", {"printer"}},
    {"English.", {"Many"}},
    {"Many", {"desktop"}},
    {"now", {"use"}},
    {"use", {"Lorem"}},
    {"default", {"modeltext,"}},
    {"modeltext,", {"and"}},
    {"printing", {"and"}},
    {"ipsum'", {"will"}},
    {"sites", {"still"}},
    {"infancy.", {"Various"}},
    {"evolved", {"overhe"}},
    {"overhe", {"years,"}},
    {"PageMaker", {"including"}},
    {"years,", {"sometimes"}},
    {"sometimes", {"on", "by"}},
    {"accident,", {"sometimes"}}
};

 std::unordered_map<std::string, std::unordered_set<std::string>> TEST_READ = Read(FileNameToRead);
 
 
 
 std::unordered_map<std::string, std::unordered_set<std::string>> wordWrite = {
   {"humour", {"and"}},
    {"(injected", {"humour"}},
    {"passages,", {"and"}},
    {"an", {"unknown"}},
    {"sheets", {"containing"}},
    {"unchanged.", {"It"}},
    {"text", {"ever", "of"}},
    {"typesetting,", {"remaining"}},
    {"industry's", {"standard"}},
    {"leap", {"into"}},
    {"centuries,", {"but"}},
    {"content", {"here',", "of"}},
    {"'Content", {"here,"}},
    {"more-or-less", {"normal"}},
    {"1960s", {"with"}},
    {"was", {"popularised"}},
    {"specimen", {"book."}},
    {"has", {"a", "survived", "been"}},
    {"typesetting", {"industry."}},
    {"in", {"their", "the"}},
    {"purpose", {"(injected"}},
    {"manyweb", {"sites"}},
    {"it", {"look", "has", "to"}},
    {"dummy", {"text"}},
    {"since", {"the"}},
    {"Letraset", {"sheets"}},
    {"book.", {"It"}},
    {"is", {"that", "a", "simply"}},
    {"like", {"readable", "Aldus"}},
    {"also", {"the"}},
    {"only", {"five"}},
    {"to", {"using", "make"}},
    {"fact", {"that"}},
    {"industry.", {"Lorem"}},
    {"looking", {"at"}},
    {"into", {"electronic"}},
    {"uncover", {"manyweb"}},
    {"of", {"letters,", "a", "Lorem", "Letraset", "using", "type", "the"}},
    {"essentially", {"unchanged."}},
    {"survived", {"not"}},
    {"took", {"a"}},
    {"opposed", {"to"}},
    {"make", {"a"}},
    {"desktop", {"publishing"}},
    {"be", {"distracted"}},
    {"when", {"looking", "an"}},
    {"and", {"the", "a", "web", "more", "scrambled", "typesetting"}},
    {"1500s,", {"when"}},
    {"not", {"only"}},
    {"letters,", {"as"}},
    {"the", {"readable", "like).", "release", "1960s", "leap", "1500s,", "industry's", "printing"}},
    {"standard", {"dummy"}},
    {"publishing", {"packages", "software"}},
    {"electronic", {"typesetting,"}},
    {"at", {"its"}},
    {"It", {"was", "has"}},
    {"their", {"infancy.", "default"}},
    {"Lorem", {"Ipsum.It", "Ipsum"}},
    {"look", {"like"}},
    {"web", {"page"}},
    {"a", {"search", "more-or-less", "page", "reader", "long", "type", "galley"}},
    {"scrambled", {"it"}},
    {"remaining", {"essentially"}},
    {"search", {"for"}},
    {"simply", {"dummy"}},
    {"versions", {"have", "of"}},
    {"been", {"the"}},
    {"more", {"recently"}},
    {"galley", {"of"}},
    {"Various", {"versions"}},
    {"readable", {"English.", "content"}},
    {"have", {"evolved"}},
    {"containing", {"Lorem"}},
    {"reader", {"will"}},
    {"with", {"desktop", "the"}},
    {"but", {"also"}},
    {"by", {"accident,", "the"}},
    {"ever", {"since"}},
    {"type", {"specimen", "and"}},
    {"recently", {"with"}},
    {"popularised", {"in"}},
    {"software", {"like"}},
    {"Aldus", {"PageMaker"}},
    {"Ipsum", {"as", "passages,", "has", "is"}},
    {"including", {"versions"}},
    {"for", {"'lorem"}},
    {"Ipsum.It", {"is"}},
    {"printer", {"took"}},
    {"long", {"established"}},
    {"established", {"fact"}},
    {"on", {"purpose"}},
    {"its", {"layout."}},
    {"using", {"'Content", "Lorem"}},
    {"that", {"it", "a"}},
    {"'lorem", {"ipsum'"}},
    {"release", {"of"}},
    {"will", {"uncover", "be"}},
    {"distracted", {"by"}},
    {"page", {"editors", "when"}},
    {"layout.", {"The"}},
    {"editors", {"now"}},
    {"point", {"of"}},
    {"five", {"centuries,"}},
    {"normal", {"distribution"}},
    {"distribution", {"of"}},
    {"as", {"their", "opposed"}},
    {"packages", {"and"}},
    {"here,", {"content"}},
    {"here',", {"making"}},
    {"The", {"point"}},
    {"still", {"in"}},
    {"making", {"it"}},
    {"unknown", {"printer"}},
    {"English.", {"Many"}},
    {"Many", {"desktop"}},
    {"now", {"use"}},
    {"use", {"Lorem"}},
    {"default", {"modeltext,"}},
    {"modeltext,", {"and"}},
    {"printing", {"and"}},
    {"ipsum'", {"will"}},
    {"sites", {"still"}},
    {"infancy.", {"Various"}},
    {"evolved", {"overhe"}},
    {"overhe", {"years,"}},
    {"PageMaker", {"including"}},
    {"years,", {"sometimes"}},
    {"sometimes", {"on", "by"}},
    {"accident,", {"sometimes"}},
    {"sdoigflas;", {"dwfgiaeop;lsdfj"}},
    {"dwfgiaeop;lsdfj", {"dsaifjasdlfkjdsifj"}},
    {"dsaifjasdlfkjdsifj", {"dsifjioasdjfio;asjf"}},
    {"dsifjioasdjfio;asjf", {"osdsjfioadfa"}},
    {"osdsjfioadfa", {"ddsdhflouasdfuhhr"}},
    {"ddsdhflouasdfuhhr", {"dhfdshf"}},
    {"dhfdshf", {"dsfhlwdaf"}},
    {"dsfhlwdaf", {"dsfgdsaf"}},
    {"dsfgdsaf", {"cflsf"}},
};


 
 std::vector<std::string> Words = Split("sdoigflas; dwfgiaeop;lsdfj dsaifjasdlfkjdsifj dsifjioasdjfio;asjf osdsjfioadfa ddsdhflouasdfuhhr dhfdshf  dsfhlwdaf dsfgdsaf cflsf"); 
 
 Write(wordWrite, Words, FileNameToWrite);
 
 wordWrite.insert({"ffffffff", {"ssssssssssssss"}});
 
 std::unordered_map<std::string, std::unordered_set<std::string>> TEST_WRITE = Read(FileNameToWrite);
 
 try {
 
 	assert_that(TEST_READ == wordRead, "[-]Failed: Problem in function Read()", "[+]Passed: No problem in function Read()");
 	assert_that(TEST_WRITE != wordWrite, "[-]Failed: Problem in function Write()", "[+]Passed: No problem in function Write()");
 
 }
 catch(std::runtime_error &e) {
 
 	std::cout << "Assertion failed: " << e.what() << std::endl;
 
 }
 
 

}
